### ISSUE TITLE
Avoiding core manipulation

### ISSUE THREAD

**Issue by 1blankz7** [andrelohmann/silverstripe-cache-backends#1]
Can we use the backends without copying something into the core directory?

**Comment by andrelohmann** [comment]
It's not possible, because the Path to the Zend Libraries is hardcoded and
the the Zend method to use some custom path isn't hand through by ss_cache

Can we use the backends without copying something into the core directory?

—
Reply to this email directly or view it on GitHub
https://github.com/andrelohmann/silverstripe-cache-backends/issues/1.
